# Practica en la realizacion de las funciones de la api

importaciones

In [2]:
import pandas as pd

## Funcion PlayTimeGenre

In [9]:
df_PlayTimeGenre = pd.read_parquet("data/play_time_genres.parquet")
df_PlayTimeGenre.columns

Index(['genres', 'year', 'playtime_forever'], dtype='object')

In [10]:
def PlayTimeGenre( genero : str ):
    """
    Funcion que devuelve el año con mas horas jugadas para dicho género.
    """
    generos = df_PlayTimeGenre[df_PlayTimeGenre["genres"] == genero] 
    if generos.empty: 
        return f"No se encontraron datos para el género {genero}"
    año_max = generos.loc[generos["playtime_forever"].idxmax()]
    result = {
        'Genero': genero,
        'Año con Más Horas Jugadas': int(año_max["year"]),
        'Total de Horas Jugadas': año_max["playtime_forever"]
    }

    return result

In [11]:
PlayTimeGenre("Action")

{'Genero': 'Action',
 'Año con Más Horas Jugadas': 2012,
 'Total de Horas Jugadas': 18096708.533333335}

## Funcion UserForGenre

In [12]:
df_UserForGenre = pd.read_parquet("data/user_for_genre_part_1.parquet")
df_UserForGenre.columns

Index(['genres', 'user_id', 'playtime_forever'], dtype='object')

In [13]:
def UserForGenre(genero: str):
    """
    Función que devuelve el usuario que acumula más horas jugadas para el género dado 
    y el total de horas jugadas para ese género.
    """
    # Filtrar el DataFrame por el género dado
    generos2 = df_UserForGenre[df_UserForGenre["genres"] == genero]
    
    # Obtener el usuario con más horas jugadas para ese género
    user_max = generos2.loc[generos2["playtime_forever"].idxmax()]["user_id"]
    
    # Calcular el total de horas jugadas para ese género
    horas_total = generos2["playtime_forever"].sum()

    # Crear el diccionario de resultados
    result = {
        "Genero": genero,
        "Usuario con Más Horas Jugadas": user_max,
        "Total de Horas Jugadas": horas_total
    }
    
    return result

In [14]:
UserForGenre("Action")

{'Genero': 'Action',
 'Usuario con Más Horas Jugadas': 'Sp3ctre',
 'Total de Horas Jugadas': 29704.216666666667}

In [15]:
df_UserForGenre2 = pd.read_parquet("data/user_for_genre_part_2.parquet")
df_UserForGenre2.columns

Index(['genres', 'playtime_forever', 'ranking'], dtype='object')

In [16]:
def UserForGenre2(genero: str):
    """
    Función que devuelve un DataFrame filtrado por el género dado y las horas jugadas por año para ese género.
    """
    # Filtrar el DataFrame por el género dado
    generos3 = df_UserForGenre2[df_UserForGenre2["genres"] == genero]
   
    # Calcular las horas jugadas por año para ese género
    horas_x_año3 = generos3["playtime_forever"].sum()
    
    # Crear el DataFrame con los datos filtrados y las horas jugadas por año
    df_result = pd.DataFrame({
        "Genero": [genero],
        "Total de Horas Jugadas hasta ahora": [horas_x_año3]
    })

    return df_result

In [17]:
UserForGenre2("Adventure")

      Genero  Total de Horas Jugadas hasta ahora
0  Adventure                        1.680433e+07

## Funcion UsersRecommend

In [18]:
df_UsersRecommend = pd.read_parquet("data/UsersRecommend.parquet")
df_UsersRecommend

               anio   id_game                          app_name  \
anio
2010.0 3     2010.0     440.0                   Team Fortress 2
       8     2010.0    4000.0                       Garry's Mod
       6     2010.0    1250.0                     Killing Floor
2011.0 100   2011.0  105600.0                          Terraria
       23    2011.0     440.0                   Team Fortress 2
       27    2011.0     620.0                          Portal 2
2012.0 112   2012.0     440.0                   Team Fortress 2
       198   2012.0  105600.0                          Terraria
       115   2012.0     570.0                            Dota 2
2013.0 253   2013.0     570.0                            Dota 2
       250   2013.0     440.0                   Team Fortress 2
       267   2013.0    4000.0                       Garry's Mod
2014.0 613   2014.0     570.0                            Dota 2
       1309  2014.0  304930.0                          Unturned
       1145  2014.0  252490.0                              Rust
2015.0 1376  2015.0     730.0  Counter-Strike: Global Offensive
       1373  2015.0     570.0                            Dota 2
       1635  2015.0  218620.0                          PAYDAY 2

             num_reviews_positivas
anio
2010.0 3                         5
       8                         4
       6                         3
2011.0 100                      36
       23                       35
       27                       30
2012.0 112                     112
       198                      72
       115                      60
2013.0 253                     388
       250                     332
       267                     230
2014.0 613                     912
       1309                    656
       1145                    585
2015.0 1376                    466
       1373                    348
       1635                    324

In [19]:
def UsersRecommend( año : int ):
    """
    Funcion que devuelve el top 3 de juegos MÁS recomendados por usuarios para el año dado.
    """
    df_año= df_UsersRecommend[df_UsersRecommend["anio"]== año]
    if type(año) != int:
        return {"Debes colocar el año en entero, Ejemplo:2012"}
    if año < df_UsersRecommend["anio"].min() or año > df_UsersRecommend["anio"].max():
        return {"Año no encontrado"}
    df_ordenado_recomendacion = df_año.sort_values(by="num_reviews_positivas", ascending=False)
    top_3_juegos = df_ordenado_recomendacion.head(3)[["app_name","num_reviews_positivas"]]
    result3 ={
        "Año": año,
        "Top 3 Juegos Más Recomendados": top_3_juegos.to_dict(orient='records')
    }
    return result3

In [20]:
UsersRecommend(2015)

{'Año': 2015,
 'Top 3 Juegos Más Recomendados': [{'app_name': 'Counter-Strike: Global Offensive',
   'num_reviews_positivas': 466},
  {'app_name': 'Dota 2', 'num_reviews_positivas': 348},
  {'app_name': 'PAYDAY 2', 'num_reviews_positivas': 324}]}

## Funcion UsersWorstDeveloper

In [21]:
df_UsersWorstDeveloper = pd.read_parquet("data/UsersWorstDeveloper.parquet")
df_UsersWorstDeveloper

              anio              developer  num_reviews_negativas
anio
2011.0 1    2011.0           Broken Rules                      2
       0    2011.0             1C Company                      1
       2    2011.0                  Valve                      1
2012.0 3    2012.0                  Valve                      1
       4    2012.0               Volition                      1
2013.0 48   2013.0    Valor no disponible                     11
       39   2013.0  Phosphor Games Studio                     10
       25   2013.0      Facepunch Studios                      7
2014.0 231  2014.0    Valor no disponible                     90
       219  2014.0   Trek Industries, Inc                     56
       62   2014.0    Bohemia Interactive                     50
2015.0 436  2015.0    Valor no disponible                    121
       303  2015.0      Facepunch Studios                     89
       259  2015.0    Bohemia Interactive                     60

In [22]:
def UsersWorstDeveloper( año : int ):
    """
    Funcion que devuelve el top 3 de desarrolladoras con juegos MENOS 
    recomendados por usuarios para el año dado.
    """
    df_año2 = df_UsersWorstDeveloper[df_UsersWorstDeveloper["anio"]== año]
    if type(año) != int:
        return {"Debes colocar el año en entero, Ejemplo:2012"}
    if año < df_UsersRecommend["anio"].min() or año > df_UsersRecommend["anio"].max():
        return {"Año no encontrado "}
    df_ordenado_recomendacion2 = df_año2.sort_values(by="num_reviews_negativas", ascending=False)
    top_3_developers = df_ordenado_recomendacion2[["developer","num_reviews_negativas"]]
    result4 = {
        'Año': año,
        'Top 3 Desarrolladoras Menos Recomendadas': top_3_developers.to_dict(orient="records")
    }
    return result4

In [23]:
UsersWorstDeveloper(2015)

{'Año': 2015,
 'Top 3 Desarrolladoras Menos Recomendadas': [{'developer': 'Valor no disponible',
   'num_reviews_negativas': 121},
  {'developer': 'Facepunch Studios', 'num_reviews_negativas': 89},
  {'developer': 'Bohemia Interactive', 'num_reviews_negativas': 60}]}

## funcion developer( desarrollador : str ): 
Cantidad de items y porcentaje de contenido Free por año según empresa desarrolladora. Ejemplo de retorno:

In [66]:
df_developer = pd.read_parquet("data/developer.parquet")
df_developer

,developer,Cantidad de Juegos por Developer,Porcentaje de Juegos Gratuitos
0,+7 Software,3,0.0
1,"+Mpact Games, LLC.",2,0.0
2,.M.Y.W.,2,0.0
3,.ez Games,5,0.0
4,07th Expansion,11,0.0
...,...,...,...
10926,致意,4,0.0
10927,萌石游戏,4,0.0
10928,高考恋爱委员会,4,100.0
10929,"高考恋爱委员会,Days",4,0.0
10930,"高考恋爱委员会,橘子班",8,0.0

In [67]:
def Developer(nombre_desarrollador):
    """
    ingresa numbre de desarrollador
    devuelve: Cantidad de items y porcentaje de contenido Free según empresa desarrolladora
    """
    try:
        # Filtrar el DataFrame por el nombre del desarrollador
        desarrollador_filtrado = df_developer[df_developer["developer"] == str(nombre_desarrollador)]
        
        if desarrollador_filtrado.empty:
            return {"error": "No se encontró ningún desarrollador con ese nombre."}
        
        # Obtener la cantidad de juegos del desarrollador filtrado
        cantidad_juegos = desarrollador_filtrado["Cantidad de Juegos por Developer"].iloc[0]
        
        # Obtener el porcentaje de juegos gratuitos del desarrollador filtrado
        porcentaje_free = desarrollador_filtrado["Porcentaje de Juegos Gratuitos"].iloc[0]
        
        resultado = {
                "Nombre del desarrollador": nombre_desarrollador,
                "Cantidad de juegos desarrollados: " : cantidad_juegos,
                "Porcentaje de ellos free: ": int(porcentaje_free)
                    }

        return resultado
    
    except Exception as e:
        return {"error": str(e)}

In [69]:
Developer('07th Expansion')

{'Nombre del desarrollador': '07th Expansion',
 'Cantidad de juegos desarrollados: ': 11,
 'Porcentaje de ellos free: ': 0.0}

## Funciones sentiment_analysis

In [27]:
df_Sentiment_Analysis = pd.read_parquet("data/sentiment_analysis.parquet")
df_Sentiment_Analysis

,developer,cant_sentiment_negative,cant_sentiment_neutral,cant_sentiment_positive
0,07th Expansion,0,3,0
1,"10th Art Studio,Adventure Productions",0,2,0
2,10tons Ltd,0,3,0
3,11 bit studios,27,135,21
4,14° East,1,1,0
...,...,...,...,...
2085,xXarabongXx,0,3,0
2086,△○□× (Miwashiba),0,6,4
2087,"インレ,Inre",0,4,1
2088,橘子班,3,6,3
2089,"高考恋爱委员会,橘子班",0,8,0

In [28]:
def sentiment_analysis( desarrollador : str ):
    """
    Funcion que devuelve un diccionario con el nombre de la desarrolladora como llave y una lista 
    con la cantidad total de registros de reseñas de usuarios que se encuentren categorizados con 
    un análisis de sentimiento como valor.
    """
    if type(desarrollador) != str:
        return "Debes colocar un developer de tipo str, EJ:'07th Expansion'"
    if len(desarrollador) == 0:
        return "Debes colocar un developer en tipo String"
    
    # Filtrar el DataFrame por el desarrollador dado
    df_desarrollador = df_Sentiment_Analysis[df_Sentiment_Analysis["developer"] == desarrollador]
    
    # Sumar el número total de reseñas negativas, neutrales y positivas
    reseñas_negativas = df_desarrollador["cant_sentiment_negative"].sum()
    reseñas_neutrales = df_desarrollador["cant_sentiment_neutral"].sum()
    reseñas_positivas = df_desarrollador["cant_sentiment_positive"].sum()

    # Crear el diccionario de resultados
    resultados = {
        "El desarrollador: ": desarrollador,
        "tiene de reseñas Negativas": reseñas_negativas,
        "tiene de reseñas Neutrales": reseñas_neutrales,
        "tiene de reseñas Positivas": reseñas_positivas
    }
    
    return resultados

In [29]:
print(df_Sentiment_Analysis.columns)

Index(['developer', 'cant_sentiment_negative', 'cant_sentiment_neutral',
       'cant_sentiment_positive'],
      dtype='object')

In [30]:
sentiment_analysis("Valve")

{'El desarrollador: ': 'Valve',
 'tiene de reseñas Negativas': 731,
 'tiene de reseñas Neutrales': 5712,
 'tiene de reseñas Positivas': 3373}

## def userdata( User_id : str ): 
Debe devolver cantidad de dinero gastado por el usuario, el porcentaje de recomendación en base a reviews.recommend y cantidad de items.

In [3]:
df_userdata = pd.read_parquet('data/userdata.parquet')
df_userdata

,user_id,anio,total_price_por_usuario,cantidad_total_juegos_por_usuario,porcentaje_recomendacion
0,76561197970982479,2011.0,29.98,3,33.333333
1,js41637,2014.0,29.98,3,33.333333
2,evcentric,NaN,68.94,6,16.666667
3,doctr,2013.0,99.95,6,16.666667
4,maplemage,2014.0,49.97,4,25.000000
...,...,...,...,...,...
57392,How51,2014.0,39.97,9,11.111111
57393,76561198111410893,2014.0,74.96,9,11.111111
57394,zaza147,2015.0,49.96,9,11.111111
57395,lifeonhigh,2015.0,44.95,9,11.111111
57396,EchoXSilence,NaN,89.96,9,0.000000

In [4]:
def userdata(user_id):
    # Filtrar el DataFrame por user_id
    usuario_filtrado = df_userdata[df_userdata['user_id'] == user_id]
    
    # Obtener la cantidad de dinero gastado por el usuario
    dinero_gastado = usuario_filtrado['total_price_por_usuario'].iloc[0]
    
    # Obtener el porcentaje de recomendación en base a reviews.recommend
    porcentaje_recomendacion = usuario_filtrado['porcentaje_recomendacion'].iloc[0]
    
    # Obtener la cantidad de items
    cantidad_items = usuario_filtrado['cantidad_total_juegos_por_usuario'].iloc[0]
    
    resultados = {
        "El user_id: ": user_id,
        "gasto en total: ": dinero_gastado,
        "porcentaje de recomendacion": porcentaje_recomendacion,
        "y compro en total:": cantidad_items
    }
    
    return resultados

In [5]:
userdata('How51')

{'El user_id: ': 'How51',
 'gasto en total: ': 39.97,
 'porcentaje de recomendacion': 11.11111111111111,
 'y compro en total:': 9}

def best_developer_year( año : int ): Devuelve el top 3 de desarrolladores con juegos MÁS recomendados por usuarios para el año dado. (reviews.recommend = True y comentarios positivos)

In [34]:
df_best_developer = pd.read_parquet('data/UsersbestDeveloper.parquet')
df_best_developer

               anio             developer  num_reviews_positivas
anio
2010.0 7     2010.0                 Valve                     10
       2     2010.0     Facepunch Studios                      4
       6     2010.0  Tripwire Interactive                      3
2011.0 76    2011.0                 Valve                     91
       55    2011.0              Re-Logic                     36
       37    2011.0           Grey Havens                     15
2012.0 177   2012.0                 Valve                    191
       138   2012.0              Re-Logic                     72
       176   2012.0   Valor no disponible                     60
2013.0 447   2013.0   Valor no disponible                    659
       448   2013.0                 Valve                    588
       274   2013.0     Facepunch Studios                    305
2014.0 1003  2014.0   Valor no disponible                   1657
       1004  2014.0                 Valve                   1267
       634   2014.0     Facepunch Studios                   1075
2015.0 1690  2015.0   Valor no disponible                   1006
       1691  2015.0                 Valve                    847
       1240  2015.0     Facepunch Studios                    464

In [35]:
def best_developer_year( año : int ):
    """
    Funcion que devuelve el top 3 de desarrolladoras con juegos MENOS 
    recomendados por usuarios para el año dado.
    """
    df_año2 = df_best_developer[df_best_developer["anio"]== año]
    if type(año) != int:
        return {"Debes colocar el año en entero, Ejemplo:2012"}
    if año < df_best_developer["anio"].min() or año > df_best_developer["anio"].max():
        return {"Año no encontrado "}
    df_ordenado_recomendacion2 = df_año2.sort_values(by="num_reviews_positivas", ascending=False)
    top_3_developers = df_ordenado_recomendacion2[["developer","num_reviews_positivas"]]
    result4 = {
        'Año': año,
        'Top 3 Desarrolladoras mas Recomendados': top_3_developers.to_dict(orient="records")
    }
    return result4

In [36]:
best_developer_year(2010)

{'Año': 2010,
 'Top 3 Desarrolladoras mas Recomendados': [{'developer': 'Valve',
   'num_reviews_positivas': 10},
  {'developer': 'Facepunch Studios', 'num_reviews_positivas': 4},
  {'developer': 'Tripwire Interactive', 'num_reviews_positivas': 3}]}